# Generated by Django 4.2.24 on 2025-09-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastroitens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=100, verbose_name='Produto')),
                ('lote', models.CharField(max_length=15, verbose_name='Lote')),
                ('validade', models.DateField(verbose_name='Validade')),
                ('fornecedor', models.CharField(max_length=50, verbose_name='Fornecedor')),
                ('quantidade', models.CharField(max_length=5, verbose_name='Quantidade')),
                ('unidade', models.CharField(choices=[('UN', 'Unidade'), ('CX', 'Caixa'), ('PCT', 'PCT')], default='UN', max_length=5, verbose_name='Unidade de Medida')),
            ],
        ),
    ]
