# Generated by Django 4.2.24 on 2025-09-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastroitens',
            name='fornecedor',
            field=models.CharField(max_length=50, verbose_name='Fabricante'),
        ),
        migrations.AlterField(
            model_name='cadastroitens',
            name='quantidade',
            field=models.IntegerField(verbose_name='Quantidade'),
        ),
    ]
