# Generated by Django 4.2.24 on 2025-09-18 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_cadastroitens_fornecedor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Produto')),
            ],
        ),
        migrations.AlterField(
            model_name='cadastroitens',
            name='fornecedor',
            field=models.CharField(max_length=50, verbose_name='Fornecedor'),
        ),
        migrations.AlterField(
            model_name='cadastroitens',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='inventario.produto'),
        ),
    ]
