# Generated by Django 4.2.24 on 2025-09-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_produto_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastroitens',
            name='origem',
            field=models.CharField(choices=[('Almoxarifado', 'Almoxarifado'), ('Doação', 'Doação'), ('Empréstimo', 'Empréstimo')], default='Almoxarifado', max_length=15, verbose_name='Origem'),
        ),
    ]
