# Generated by Django 4.2.24 on 2025-09-24 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_movimentacao_movimentacaoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaoitem',
            name='descricao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimentacao_descricao', to='inventario.produto'),
        ),
        migrations.AlterField(
            model_name='movimentacaoitem',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacao_produto', to='inventario.produto'),
        ),
    ]
