# Generated by Django 4.2.24 on 2025-10-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_movimentacaoitem_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='tipo_movimentacao',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('baixa', 'Baixa por requisição'), ('transferencia', 'Transferência'), ('devolucao', 'Devolução'), ('vencidos', 'Validade vencida')], max_length=50),
        ),
    ]
