# Generated by Django 4.2.24 on 2025-10-09 10:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_alter_movimentacao_tipo_movimentacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastroitens',
            name='data',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
